# Generated by Django 5.2.4 on 2025-07-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('shop', '0007_salerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='purchased_products',
            field=models.ManyToManyField(blank=True, related_name='buyers_purchased', to='shop.product'),
        ),
    ]
