# Generated by Django 5.2.4 on 2025-08-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_purchased_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='theme_preference',
            field=models.CharField(blank=True, choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10, null=True),
        ),
    ]
