# Generated by Django 5.2.4 on 2025-07-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_image_product_brand_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='category/%Y/%m/%d'),
        ),
    ]
