# Generated by Django 5.2.4 on 2025-09-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_salerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_type',
            field=models.CharField(choices=[('none', 'No Tax'), ('food', 'Food (6%)'), ('home', 'Home (21%)')], default='none', max_length=20),
        ),
    ]
