# Generated by Django 5.2.4 on 2025-08-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delivired',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='is_delivired'),
        ),
    ]
